[package]
name = "javy-plugin-processing"
version = "0.0.0"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Logic for initializing Javy plugins"
homepage = "https://github.com/bytecodealliance/javy/tree/main/crates/plugin-processing"
repository = "https://github.com/bytecodealliance/javy/tree/main/crates/plugin-processing"
categories = ["wasm"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
walrus.workspace = true
wasmparser.workspace = true
javy-motor-engine = { path = "../motor-engine" }

wasm-opt = { workspace = true }
tempfile = { workspace = true }
